# -*- coding: utf-8 -*-
"""page_funnel_visits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/JorgeEdu018/a5c0dd2143fd300f69da8d3b331b5e5a/page_funnel_visits.ipynb
"""

import pandas as pd

"""Import all the files"""

visits = pd.read_csv('visits.csv',
                     parse_dates=[1])
cart = pd.read_csv('cart.csv',
                   parse_dates=[1])
                   
checkout = pd.read_csv('checkout.csv',
                       parse_dates=[1])
purchase = pd.read_csv('purchase.csv',
                       parse_dates=[1])

"""Step 1: Inspect the DataFrames using `print` and `head`"""

print(visits.head(5))
print(cart.head(5))
print(checkout.head(5))
print(purchase.head(5))

"""Step 2: Left merging visits and cart"""

visits_cart = visits.merge(cart, how = 'left')
print(visits_cart)

"""Step 3: How long is `visits_cart`?"""

Total_visits = len(visits_cart)
print(Total_visits)

"""Step 4: How many timestamps are null for `cart_time`?"""

CT = len(visits_cart[visits_cart.cart_time.isnull()])
print(CT)

"""Step 5: What percentage only visited?"""

Percentege_visited = CT/Total_visits
print(Percentege_visited)

"""Step 6: What percentage placed a t-shirt in their cart but did not checkout?"""

cart_checkout = cart.merge(checkout, how = 'left')
print(cart_checkout)
null_car_checkout = len(cart_checkout[cart_checkout.checkout_time.isnull()])
print(null_car_checkout)
cart_not_check = float(null_car_checkout) / float(len(cart))
print("Cart but not checkout:", cart_not_check)

"""Step 7: Merge it all together"""

all_data = visits_cart.merge(cart_checkout, how='left').merge(purchase, how='left')

print(all_data)

"""Step 8: % of users who got to checkout but did not purchase"""

reached_checkout = all_data[~all_data.checkout_time.isnull()]
checkout_not_purchase = all_data[(all_data.purchase_time.isnull()) & (~all_data.checkout_time.isnull())]
checkout_not_purchase_percent = float(len(checkout_not_purchase)) / float(len(reached_checkout))

print("% of users who got to checkout but did not purchase:",checkout_not_purchase_percent)

"""Step 9: check each part of the funnel, let's print all 3 of them again"""

print("{} percent of users who visited the page did not add a t-shirt to their cart".format(round(Percentege_visited*100, 2)))
print("{} percent of users who added a t-shirt to their cart did not checkout".format(round(cart_not_check*100, 2)))
print("{} percent of users who made it to checkout  did not purchase a shirt".format(round( checkout_not_purchase_percent*100, 2)))

"""*The weakest part of the funnel is clearly getting a person who visited the site to add a tshirt to their cart. Once they've added a t-shirt to their cart it is fairly likely they end up purchasing it. A suggestion could be to make the add-to-cart button more prominent on the front page.*


Step 10: adding new column
"""

all_data['time_to_purchase'] = all_data.purchase_time - all_data.visit_time

"""Step 11: examine the results"""

print(all_data.time_to_purchase)

"""Step 12: average time to purchase"""

print(all_data.time_to_purchase.mean())

